### ISSUE TITLE
removing excess spikes

### ISSUE THREAD

**Issue by mariapfj** [CINPLA/expipe-plugin-cinpla#85]
Getting an error message when spikesorting projects\ec109\maria\mec-social-nwb\actions\137-310121-7 and projects\ec109\maria\novel-env-nwb\145-211021-1

ValueError: The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function

There already seems to be a function for removing excess spikes in src/expipe_plugin_cinpla/scripts/curation.py  (I'm assuming this is the one referred to in the error message), any idea why this issue occurs for these specific recordings? Do I need to run the function in question manually? (if yes feel free to mention specifically which variables it requires) :)

**Comment by alejoe91** [comment]
Hi @mariapfj 
Is that the full error? I'll take a look

**Comment by mariapfj** [comment]
Postprocessing
	Extracting waveforms
ERROR: unable to process 137-310121-7
Traceback (most recent call last):
  File "/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/widgets/process.py", line 300, in on_run
    process.process_ecephys(
  File "/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/process.py", line 245, in process_ecephys
    compute_and_set_unit_groups(sorting, recording_cmr)
  File "/fp/projects01/ec109/software/expipe-plugin-cinpla/src/expipe_plugin_cinpla/scripts/utils.py", line 295, in compute_and_set_unit_groups
    we_mem = si.extract_waveforms(recording, sorting, folder=None, mode="memory", sparse=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fp/homes01/u01/ec-mariapfj/.local/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py", line 1670, in extract_waveforms
    we = WaveformExtractor.create(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fp/homes01/u01/ec-mariapfj/.local/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py", line 271, in create
    raise ValueError(
ValueError: The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function
